# INDICES
INDICES = [
    "^NSEI",       # NIFTY 50
    "^NSEBANK",    # BANK NIFTY
    "^BSESN"       # SENSEX
]

# NIFTY 50 (Large Cap)
LARGE_CAP = [
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "BHARTIARTL", "ITC", "SBIN", "LICI", "HINDUNILVR",
    "LT", "BAJFINANCE", "HCLTECH", "KOTAKBANK", "AXISBANK", "SUNPHARMA", "TITAN", "ULTRACEMCO", "MARUTI",
    "ASIANPAINT", "ADANIENT", "BAJAJFINSV", "NTPC", "TATAMOTORS", "POWERGRID", "ONGC", "M&M", "COALINDIA",
    "TATASTEEL", "JSWSTEEL", "ADANIPORTS", "HDFCLIFE", "SBILIFE", "GRASIM", "BAJAJ-AUTO", "TECHM",
    "WIPRO", "DRREDDY", "CIPLA", "APOLLOHOSP", "TATACONSUM", "BRITANNIA", "EICHERMOT", "INDUSINDBK",
    "DIVISLAB", "HEROMOTOCO", "HINDALCO", "LTIM", "BPCL", "UPL"
]

ALL_STOCKS = {
    "Indices (NIFTY/BANKNIFTY/SENSEX)": INDICES,
    "Large Cap (Nifty 50 Stocks)": LARGE_CAP,
}
