# NIFTY 50 (Large Cap)
LARGE_CAP = [
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "BHARTIARTL", "ITC", "SBIN", "LICI", "HINDUNILVR",
    "LT", "BAJFINANCE", "HCLTECH", "KOTAKBANK", "AXISBANK", "SUNPHARMA", "TITAN", "ULTRACEMCO", "MARUTI",
    "ASIANPAINT", "ADANIENT", "BAJAJFINSV", "NTPC", "TATAMOTORS", "POWERGRID", "ONGC", "M&M", "COALINDIA",
    "TATASTEEL", "JSWSTEEL", "ADANIPORTS", "HDFCLIFE", "SBILIFE", "GRASIM", "BAJAJ-AUTO", "TECHM",
    "WIPRO", "DRREDDY", "CIPLA", "APOLLOHOSP", "TATACONSUM", "BRITANNIA", "EICHERMOT", "INDUSINDBK",
    "DIVISLAB", "HEROMOTOCO", "HINDALCO", "LTIM", "BPCL", "UPL"
]

# NIFTY Midcap Select (Representative Mid Caps)
MID_CAP = [
    "TRENT", "BEL", "TVSMOTOR", "CHOLAFIN", "INDHOTEL", "ABB", "SIEMENS", "TATACOMM", "PERSISTENT",
    "MPHASIS", "OBEROIRLTY", "ABCAPITAL", "YESBANK", "IDFCFIRSTB", "ASHOKLEY", "ASTRAL", "POLYCAB",
    "SRF", "JUBLFOOD", "ZEEL", "VOLTAS", "CUMMINSIND", "NAUKRI", "PAYTM", "ZOMATO", "POLICYBZR",
    "PIIND", "CONCOR", "AUROPHARMA", "LUPIN", "ALKEM", "MRF", "PAGEIND", "BOSCHLTD", "HONAUT",
    "DALBHARAT", "ACC", "AMBUJACEM", "GODREJPROP", "DLF", "M&MFIN", "LICHSGFIN", "PEL", "IGL",
    "PETRONET", "MFSL", "MAXHEALTH", "SYNGENE", "ESCORTS", "BHARATFORG"
]

# NIFTY Smallcap Select (Representative Small Caps / High Beta)
SMALL_CAP = [
    "CDSL", "BSE", "IEX", "MCX", "ANGELONE", "CAMS", "KIMS", "CYIENT", "BSOFT", "SONACOMS",
    "REDINGTON", "NBCC", "HUDCO", "IRB", "NATIONALUM", "CHAMBLFERT", "GNFC", "DEEPAKNTR",
    "TATACHEM", "RBLBANK", "IDBI", "CENTRALBK", "UCOBANK", "MAHABANK", "IOB", "GSFC",
    "JBMA", "OLECTRA", "JSL", "WELCORP", "RADICO", "DEVYANI", "SAPPHIRE", "TRIDENT",
    "SUZLON", "IDEA", "RENUKA", "ECLERX", "INTELLECT", "HAPPSTMNDS", "TANLA", "ROUTE",
    "AFFLE", "LATENTVIEW", "MAPMYINDIA", "DATAPATTNS", "MTARTECH", "PARAS", "ZENTEC"
]

ALL_STOCKS = {
    "Large Cap (Nifty 50)": LARGE_CAP,
    "Mid Cap": MID_CAP,
    "Small Cap": SMALL_CAP
}
